
"""File with all the constants, for map, characters and their stats

"""

# SCREEN AND MAP
MAP_WIDTH = 30
MAP_HEIGHT = 30
SCREEN_WIDTH = 672 #480 # 16 * 30        16 * 42 = 672
SCREEN_HEIGHT = 592 #480 # 16 * 30			16 * 37 = 592
TILE_SIZE = 16
FONT_SIZE = 16
# in tiles
SCREEN_SIZE_WIDTH = 42
SCREEN_SIZE_HEIGHT = 37

START_MESSAGE_BOX_X = 0
START_MESSAGE_BOX_Y = 30

START_INFORMATION_BOX_X = 30
START_INFORMATION_BOX_Y = 0
WIDTH_INFORMATION_BOX = 12
HEIGHT_INFORMATION_BOX = 20


PLAYER_NAME = 'pysio'

INVENTORY_BOX_X = 30
INVENTORY_BOX_Y = 20

INVENTORY_ITEMS_START_X = 31
INVENTORY_ITEMS_START_Y = 21

INVENTORY_PLACES_WIDTH = 10
INVENTORY_PLACES_HEIGHT = 14

INVENTORY_WIDTH = 12
INVENTORY_HEIGHT = 17


UI_HELMET_SLOT = (START_INFORMATION_BOX_X + (12 / 2)-1, START_INFORMATION_BOX_Y + 4)



# Enemies - map settings
MAX_ENEMIES = 15

# Indexes for images

IMAGES_INDEX_PLAYER = 0
IMAGES_INDEX_WALL = 1
IMAGES_INDEX_FLOOR = 2
IMAGES_INDEX_EMPTY_SPACE = 3
IMAGES_INDEX_WORM = 4
IMAGES_INDEX_ABHORRENT_CREATURE = 5

IMAGES_POTION_HP = 13
IMAGES_SCROLL_OF_DEATH = 14



# Monster stats
PLAYER_START_HP = 20
WORM_MAX_HP = 3
ABHORRENT_CREATURE_MAX_HP = 300


# move here all the messages
